image: docker:stable

variables:
  IMAGE_NAME: $CI_REGISTRY/$CI_PROJECT_PATH/booster

services:
    - docker:dind

stages:
  - build
  - deploy

build:
  only:
    - master
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
  after_script:
    - docker logout registry.gitlab.com
  image: docker:stable
  stage: build
  script:
    - docker build -t $IMAGE_NAME:$CI_COMMIT_SHORT_SHA -t $IMAGE_NAME:latest -f Dockerfile.prod .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - docker push $IMAGE_NAME:latest

deploy:
  only:
    - master
  image: 'vitorfhc/gcloud-envsubst'
  stage: deploy
  script:
    - echo "$SERVICE_ACCOUNT_KEY" > key.json
    - gcloud auth activate-service-account --key-file=key.json
    - gcloud config set project $GCLOUD_PROJECT
    - gcloud config set container/cluster $GCLOUD_CLUSTER
    - gcloud config set compute/zone $GCLOUD_ZONE
    - gcloud container clusters get-credentials $GCLOUD_CLUSTER --zone $GCLOUD_ZONE
    - cat booster.yaml | envsubst | kubectl apply -f -
