version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile.prod
      context: .
    ports:
      - 3000:3000

  db:
    image: mongo:4.2.1
    volumes:
      - database-volume:/data/db

volumes:
  database-volume:
