version: '3'

services:
  api:
    image: registry.gitlab.com/vitorfhc/booster/booster
    ports:
      - 3000:3000

  db:
    image: mongo:4.2.1
    volumes:
      - database-volume:/data/db

volumes:
  database-volume:
